
let arrayReservation = [];
	let calendrier=[
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">30</td><td class="fermeture">1</td><td class="fermeture">2</td><td class="fermeture">3</td><td class="fermeture">4</td><td class="fermeture">5</td><td class="fermeture">6</td></tr><tr><td class="fermeture">7</td><td class="fermeture">8</td><td class="fermeture">9</td><td class="fermeture">10</td><td class="fermeture">11</td><td class="fermeture">12</td><td class="fermeture">13</td></tr><tr><td class="fermeture">14</td><td class="fermeture">15</td><td class="fermeture">16</td><td class="fermeture">17</td><td class="fermeture">18</td><td class="fermeture">19</td><td class="fermeture">20</td></tr><tr><td class="fermeture">21</td><td class="fermeture">22</td><td class="fermeture">23</td><td class="fermeture">24</td><td class="fermeture">25</td><td class="fermeture">26</td><td class="fermeture">27</td></tr><tr><td class="fermeture">28</td><td class="fermeture">29</td><td class="fermeture">30</td><td class="fermeture">31</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">28</td><td class="clair">29</td><td class="clair">30</td><td class="clair">31</td><td class="fermeture">1</td><td class="fermeture">2</td><td class="fermeture">3</td></tr><tr><td class="fermeture">4</td><td class="fermeture">5</td><td class="fermeture">6</td><td class="fermeture">7</td><td class="fermeture">8</td><td class="fermeture">9</td><td class="fermeture">10</td></tr><tr><td class="fermeture">11</td><td class="fermeture">12</td><td class="fermeture">13</td><td class="fermeture">14</td><td class="fermeture">15</td><td class="fermeture">16</td><td class="fermeture">17</td></tr><tr><td class="fermeture">18</td><td class="fermeture">19</td><td class="fermeture">20</td><td class="fermeture">21</td><td class="fermeture">22</td><td class="fermeture">23</td><td class="fermeture">24</td></tr><tr><td class="fermeture">25</td><td class="fermeture">26</td><td class="fermeture">27</td><td class="fermeture">28</td><td class="fermeture">29</td><td class="fermeture">30</td><td class="fermeture">31</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="fermeture">1</td><td class="fermeture">2</td><td class="fermeture">3</td><td class="fermeture">4</td><td class="fermeture">5</td><td class="fermeture">6</td><td class="fermeture">7</td></tr><tr><td class="fermeture">8</td><td class="fermeture">9</td><td class="fermeture">10</td><td class="fermeture">11</td><td class="fermeture">12</td><td class="fermeture">13</td><td class="fermeture">14</td></tr><tr><td class="fermeture">15</td><td class="fermeture">16</td><td class="fermeture">17</td><td class="fermeture">18</td><td class="fermeture">19</td><td class="fermeture">20</td><td class="fermeture">21</td></tr><tr><td class="fermeture">22</td><td class="fermeture">23</td><td class="fermeture">24</td><td class="fermeture">25</td><td class="fermeture">26</td><td class="fermeture">27</td><td class="fermeture">28</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="fermeture">1</td><td class="fermeture">2</td><td class="fermeture">3</td><td class="fermeture">4</td><td class="fermeture">5</td><td class="fermeture">6</td><td class="fermeture">7</td></tr><tr><td class="fermeture">8</td><td class="fermeture">9</td><td class="fermeture">10</td><td class="fermeture">11</td><td class="fermeture">12</td><td class="fermeture">13</td><td class="fermeture">14</td></tr><tr><td class="fermeture">15</td><td class="fermeture">16</td><td class="fermeture">17</td><td class="fermeture">18</td><td class="fermeture">19</td><td class="fermeture">20</td><td class="fermeture">21</td></tr><tr><td class="fermeture">22</td><td class="fermeture">23</td><td class="fermeture">24</td><td class="fermeture">25</td><td class="fermeture">26</td><td class="fermeture">27</td><td class="fermeture">28</td></tr><tr><td class="fermeture">29</td><td class="fermeture">30</td><td class="fermeture">31</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td><td class="clair">4</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">29</td><td class="clair">30</td><td class="clair">31</td><td class="fermeture">1</td><td class="fermeture">2</td><td class="ouverture">3</td><td class="ouverture">4</td></tr><tr class="ouverture"><td class="ouverture">5</td><td class="ouverture">6</td><td class="ouverture">7</td><td class="ouverture">8</td><td class="ouverture">9</td><td class="ouverture">10</td><td class="ouverture">11</td></tr><tr><td class="ouverture">12</td><td class="ouverture">13</td><td class="ouverture">14</td><td class="ouverture">15</td><td class="ouverture">16</td><td class="ouverture">17</td><td class="ouverture">18</td></tr><tr><td class="ouverture">19</td><td class="ouverture">20</td><td class="ouverture">21</td><td class="ouverture">22</td><td class="ouverture">23</td><td class="ouverture">24</td><td class="ouverture">25</td></tr><tr><td class="ouverture">26</td><td class="ouverture">27</td><td class="ouverture">28</td><td class="ouverture">29</td><td class="ouverture">30</td><td class="clair">1</td><td class="clair">2</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">26</td><td class="clair">27</td><td class="clair">28</td><td class="clair">29</td><td class="clair">30</td><td class="ouverture">1</td><td class="ouverture">2</td></tr><tr><td class="ouverture">3</td><td class="ouverture">4</td><td class="ouverture">5</td><td class="ouverture">6</td><td class="ouverture">7</td><td class="ouverture">8</td><td class="ouverture">9</td></tr><tr><td class="ouverture">10</td><td class="ouverture">11</td><td class="ouverture">12</td><td class="ouverture">13</td><td class="ouverture">14</td><td class="ouverture">15</td><td class="ouverture">16</td></tr><tr><td class="ouverture">17</td><td class="ouverture">18</td><td class="ouverture">19</td><td class="ouverture">20</td><td class="ouverture">21</td><td class="ouverture">22</td><td class="ouverture">23</td></tr><tr><td class="ouverture">24</td><td class="ouverture">25</td><td class="ouverture">26</td><td class="ouverture">27</td><td class="ouverture">28</td><td class="ouverture">29</td><td class="ouverture">30</td></tr><tr><td class="ouverture">31</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td><td class="clair">4</td><td class="clair">5</td><td class="clair">6</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">31</td><td class="ouverture">1</td><td class="ouverture">2</td><td class="ouverture">3</td><td class="ouverture">4</td><td class="ouverture">5</td><td class="ouverture">6</td></tr><tr><td class="ouverture">7</td><td class="ouverture">8</td><td class="ouverture">9</td><td class="ouverture">10</td><td class="ouverture">11</td><td class="ouverture">12</td><td class="ouverture">13</td></tr><tr><td class="ouverture">14</td><td class="ouverture">15</td><td class="ouverture">16</td><td class="ouverture">17</td><td class="ouverture">18</td><td class="ouverture">19</td><td class="ouverture">20</td></tr><tr><td class="ouverture">21</td><td class="ouverture">22</td><td class="ouverture">23</td><td class="ouverture">24</td><td class="ouverture">25</td><td class="ouverture">26</td><td class="ouverture">27</td></tr><tr><td class="ouverture">28</td><td class="ouverture">29</td><td class="ouverture">30</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td><td class="clair">4</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">28</td><td class="clair">29</td><td class="clair">30</td><td class="ouverture">1</td><td class="ouverture">2</td><td class="ouverture">3</td><td class="ouverture">4</td></tr><tr><td class="ouverture">5</td><td class="ouverture">6</td><td class="ouverture">7</td><td class="ouverture">8</td><td class="ouverture">9</td><td class="ouverture">10</td><td class="ouverture">11</td></tr><tr><td class="ouverture">12</td><td class="ouverture">13</td><td class="ouverture">14</td><td class="ouverture">15</td><td class="ouverture">16</td><td class="ouverture">17</td><td class="ouverture">18</td></tr><tr><td class="ouverture">19</td><td class="ouverture">20</td><td class="ouverture">21</td><td class="ouverture">22</td><td class="ouverture">23</td><td class="ouverture">24</td><td class="ouverture">25</td></tr><tr><td class="ouverture">26</td><td class="ouverture">27</td><td class="ouverture">28</td><td class="ouverture">29</td><td class="ouverture">30</td><td class="ouverture">31</td><td class="clair">1</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">26</td class="clair"><td class="clair">27</td><td class="clair">28</td><td class="clair">29</td><td class="clair">30</td><td class="clair">31</td><td class="ouverture">1</td></tr><tr><td class="ouverture">2</td><td class="ouverture">3</td><td class="ouverture">4</td><td class="ouverture">5</td><td class="ouverture">6</td><td class="ouverture">7</td><td class="ouverture">8</td></tr><tr><td class="ouverture">9</td><td class="ouverture">10</td><td class="ouverture">11</td><td class="ouverture">12</td><td class="ouverture">13</td><td class="ouverture">14</td><td class="ouverture">15</td></tr><tr><td class="ouverture">16</td><td class="ouverture">17</td><td class="ouverture">18</td><td class="ouverture">19</td><td class="ouverture">20</td><td class="ouverture">21</td><td class="ouverture">22</td></tr><tr><td class="ouverture">23</td><td class="ouverture">24</td><td class="ouverture">25</td><td class="ouverture">26</td><td class="ouverture">27</td><td class="ouverture">28</td><td class="ouverture">29</td></tr><tr><td class="ouverture">30</td><td class="ouverture">31</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td><td class="clair">4</td><td class="clair">5</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">30</td><td class="clair">31</td><td class="ouverture">1</td><td class="ouverture">2</td><td class="ouverture">3</td><td class="ouverture">4</td><td class="ouverture">5</td></tr><tr><td class="ouverture">6</td><td class="ouverture">7</td><td class="ouverture">8</td><td class="ouverture">9</td><td class="ouverture">10</td><td class="ouverture">11</td><td class="ouverture">12</td></tr><tr><td class="ouverture">13</td><td class="ouverture">14</td><td class="ouverture">15</td><td class="ouverture">16</td><td class="ouverture">17</td><td class="ouverture">18</td><td class="ouverture">19</td></tr><tr><td class="ouverture">20</td><td class="ouverture">21</td><td class="ouverture">22</td><td class="ouverture">23</td><td class="ouverture">24</td><td class="ouverture">25</td><td class="ouverture">26</td></tr><tr><td class="ouverture">27</td><td class="ouverture">28</td><td class="ouverture">29</td><td class="ouverture">30</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">27</td><td class="clair">28</td><td class="clair">29</td><td class="clair">30</td><td class="ouverture">1</td><td class="ouverture">2</td><td class="ouverture">3</td></tr><tr><td class="ouverture">4</td><td class="ouverture">5</td><td class="ouverture">6</td><td class="ouverture">7</td><td class="ouverture">8</td><td class="ouverture">9</td><td class="ouverture">10</td></tr><tr><td class="ouverture">11</td><td class="ouverture">12</td><td class="ouverture">13</td><td class="ouverture">14</td><td class="ouverture">15</td><td class="ouverture">16</td><td class="ouverture">17</td></tr><tr><td class="ouverture">18</td><td class="ouverture">19</td><td class="ouverture">20</td><td class="ouverture">21</td><td class="ouverture">22</td><td class="ouverture">23</td><td class="ouverture">24</td></tr><tr><td class="ouverture">25</td><td class="ouverture">26</td><td class="ouverture">27</td><td class="ouverture">28</td><td class="ouverture">29</td><td class="ouverture">30</td><td class="ouverture">31</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="ouverture">1</td><td class="ouverture">2</td><td class="ouverture">3</td><td class="ouverture">4</td><td class="ouverture">5</td><td class="ouverture">6</td><td class="ouverture">7</td></tr><tr><td class="fermeture">8</td><td class="fermeture">9</td><td class="fermeture">10</td><td class="fermeture">11</td><td class="fermeture">12</td><td class="fermeture">13</td><td class="fermeture">14</td></tr><tr><td class="fermeture">15</td><td class="fermeture">16</td><td class="fermeture">17</td><td class="fermeture">18</td><td class="fermeture">19</td><td class="fermeture">20</td><td class="fermeture">21</td></tr><tr><td class="fermeture">22</td><td class="fermeture">23</td><td class="fermeture">24</td><td class="fermeture">25</td><td class="fermeture">26</td><td class="fermeture">27</td><td class="fermeture">28</td></tr><tr><td class="fermeture">29</td><td class="fermeture">30</td><td class="clair">1</td><td class="clair">2</td><td class="clair">3</td><td class="clair">4</td><td class="clair">5</td></tr></table>',
		'<button onclick="moisPrecedent(calendrier,mois)">____-____</button><button onclick="moisSuivant(calendrier,mois)">____+____</button><table><tr><th scope="col">Lundi</th><th scope="col">Mardi</th><th scope="col">Mercredi</th><th scope="col">Jeudi</th><th scope="col">Vendredi</th><th scope="col">Samedi</th><th scope="col">Dimanche</th></tr><tr><td class="clair">29</td><td class="clair">30</td><td class="fermeture">1</td><td class="fermeture">2</td><td class="fermeture">3</td><td class="fermeture">4</td><td class="fermeture">5</td></tr><tr><td class="fermeture">6</td><td class="fermeture">7</td><td class="fermeture">8</td><td class="fermeture">9</td><td class="fermeture">10</td><td class="fermeture">11</td><td class="fermeture">12</td></tr><tr><td class="fermeture">13</td><td class="fermeture">14</td><td class="fermeture">15</td><td class="fermeture">16</td><td class="fermeture">17</td><td class="fermeture">18</td><td class="fermeture">19</td></tr><tr><td class="fermeture">20</td><td class="fermeture">21</td><td class="fermeture">22</td><td class="fermeture">23</td><td class="fermeture">24</td><td class="fermeture">25</td><td class="fermeture">26</td></tr><tr><td class="fermeture">27</td><td class="fermeture">28</td><td class="fermeture">29</td><td class="fermeture">30</td><td class="fermeture">31</td><td class="clair">1</td><td class="clair">2</td></tr></table>'
		];	
			
		
let mois=["Décembre 2020","Janvier 2021","Février 2021","Mars 2021","Avril 2021","Mai 2021","Juin 2021","Juillet 2021","Août 2021","Septembre 2021","Octobre 2021","Novembre 2021","Décembre 2021"];
function ajoutReservation(fonction,arrayReservation){
	let reservation = {
	nom : "0",
	senior : 0,
	adulte : 0,
	enfant : 0,
	etudiant : 0,
	prix : 0
	}
	reservation.nom= document.getElementById("Nom").value;
	reservation.senior=Number(document.getElementById("senior").value);
	reservation.adulte=Number(document.getElementById("adulte").value);
	reservation.enfant=Number(document.getElementById("enfant").value);
	reservation.etudiant=Number(document.getElementById("etudiant").value);	
	prix=(reservation.senior*15)+(reservation.adulte*20)+(reservation.enfant*5)+(reservation.etudiant*15);	
	reservation.prix=prix; 
	arrayReservation[arrayReservation.length]=reservation;
	document.getElementById("commande").innerText= "Dernier achat : Votre commande de "+reservation.prix+" euros au nom de "+reservation.nom+" comprenant "+reservation.enfant+" ticket(s) enfants,"+reservation.adulte+" ticket(s) adulte, "+reservation.etudiant+" ticket(s) étudiant et "+reservation.senior+" ticket(s) senior a bien été effectuée.";
	return false;
}
function moisSuivant(calendrier,mois){	
	let compteur=0;
	let compteur2=0;
	while(compteur<mois.length){
		if(document.getElementById("mois").innerText==mois[compteur]){
			compteur2=compteur;
		}
		compteur++;
	}
	compteur2++;
	if(compteur2<0 || compteur2>(mois.length-1)){
		compteur2--;
		document.getElementById("mois").innerText=mois[compteur2];
		document.getElementById("ouverture").innerHTML=calendrier[compteur2]+"Le calendrier d'ouverture n'est pas actualiser à la date supérieur.";
	}
	else{
		document.getElementById("mois").innerText=mois[compteur2];
		document.getElementById("ouverture").innerHTML=calendrier[compteur2];
	}
	return false;	
}

function moisPrecedent(calendrier,mois){	
	let compteur=0;
	let compteur2=0;
	while(compteur<mois.length){
		if(document.getElementById("mois").innerText==mois[compteur]){
			compteur2=compteur;
		}
		compteur++;
	}
	compteur2--;
	if(compteur2<0 || compteur2>(mois.length-1)){
		compteur2++;
		document.getElementById("mois").innerText=mois[compteur2];
		document.getElementById("ouverture").innerHTML=calendrier[compteur2]+"Le calendrier d'ouverture n'est pas actualiser à la date inférieure.";
	}
	else{
		document.getElementById("mois").innerText=mois[compteur2];
		document.getElementById("ouverture").innerHTML=calendrier[compteur2];
	}
	return false;	
}

